roman-numerals: Use `iter` instead of `into_iter` when not moving
Clippy suggested
https://travis-ci.org/exercism/rust/builds/456432005
error: this .into_iter() call is equivalent to .iter() and will not move the array
   = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.212/index.html#into_iter_on_array

(compare to 75c1bf93b7045bcd25aa178a8cecf1da4bb422fc which was on
slices. Apparently this is considered a warning for slices but an error
on arrays)