forth: Don't `use` Term
I prefer to make it easier to see where `term` is being used.

Also, this causes an error in Rust 2018:

    error[E0658]: imports can only refer to extern crate names passed with `--extern` on stable channel (see issue #53130)
      --> src/lib.rs:5:5
       |
    5  |   use Term::*;
       |       ^^^^

Of course there are probably other ways to fix that, but not something I
want to do right now.