forth: Use `?` not `try!`
Would cause an error in Rust 2018:

    error: expected expression, found reserved keyword `try`
      --> src/lib.rs:72:13
       |
    72 |             try!(self.step_term(term))
       |             ^^^ expected expression